In [ ]:
import pandas as pd

animal_list_1 = ['Dog', 'Cat', 'Tiger', 'Lion']

animal_list_1

['Dog', 'Cat', 'Tiger', 'Lion']

In [ ]:
animal_series_1 = pd.Series(animal_list_1)
animal_series_1

0      Dog
1      Cat
2    Tiger
3     Lion
dtype: object

In [ ]:
#1차원 자료 구조 Series
animal_series_1 = pd.Series(animal_list_1, index=[1, 2, 3, 4])
animal_series_1

1      Dog
2      Cat
3    Tiger
4     Lion
dtype: object

In [ ]:
#리스트를 튜플로 형변환
animal_tuple_1 = tuple(animal_list_1)
type(animal_tuple_1)

tuple

In [ ]:
#튜플을 시리즈로 형변환
animal_series_2 = pd.Series(animal_tuple_1)
animal_series_2

0      Dog
1      Cat
2    Tiger
3     Lion
dtype: object

In [ ]:
people_tuple_1 = ('이순신', '19910315', '남성')
#튜플을 시리즈로 형변환 및 인덱스 임의 지정
people_series_1 = pd.Series(people_tuple_1, index = ['성명', '생년월일', '성별'])

people_series_1

성명           이순신
생년월일    19910315
성별            남성
dtype: object

In [ ]:
animal_dict = {
    '동물' : animal_list_1 + ['Monkey'],
    '나이' : [ 7, 9, 2, 3, 1 ],
    '체중' : [ 50, 30, 150, 200, 40]
}

animal_dict

{'동물': ['Dog', 'Cat', 'Tiger', 'Lion', 'Monkey'],
 '나이': [7, 9, 2, 3, 1],
 '체중': [50, 30, 150, 200, 40]}

In [ ]:
#딕셔너리를 데이터프레임으로 형변환
animal_df = pd.DataFrame(animal_dict)
type(animal_df)

pandas.core.frame.DataFrame

In [ ]:
animal_df

       동물  나이   체중
0     Dog   7   50
1     Cat   9   30
2   Tiger   2  150
3    Lion   3  200
4  Monkey   1   40

In [ ]:
import seaborn as sns

tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
#사실 상 같은 타입으로 변환한 것이므로 변화가 없다.
tips_df = pd.DataFrame(tips)
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips_df.info()
#데이터프레임의 타입, 크기, 열 개수, 각 열의 타입 등을 출력한다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
tips_df.dtypes
#데이터프레임의 각 열에 대한 타입을 출력한다

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
tips_df.head()
#맨 처음의 5개 행 출력

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips_df.tail()
#맨 마지막의 5개 행 출력

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
tips_df.loc[2:7]
#인덱스명을 기준으로 데이터 출력
#시작 인덱스인 2와 끝 인덱스인 7이 인덱스명이 된다.
#즉 수와 문자라도 상관 없다.

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4

In [ ]:
tips_df.loc[[1, 4, 7]]
#특정 인덱스(1,4,7)만 골라 출력하기
#대괄호를 두번 감싼다는 특징이 있다.

   total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
4       24.59  3.61  Female     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [ ]:
tips_df.loc[0 : 10, ['total_bill', 'tip']]
#0부터 10 인덱스까지 특정 열(total_bill, tip)만 골라 출력하기

    total_bill   tip
0        16.99  1.01
1        10.34  1.66
2        21.01  3.50
3        23.68  3.31
4        24.59  3.61
5        25.29  4.71
6         8.77  2.00
7        26.88  3.12
8        15.04  1.96
9        14.78  3.23
10       10.27  1.71

In [ ]:
tips_df.at[101, 'sex']
#특정한 인덱스 및 열만 골라 그 데이터만 출력하기

'Female'

In [ ]:
tips_df[['tip','sex']]
#특정 열만 골라 출력하기
#함수를 사용하지 않고도 대괄호를 두번 감싸 특정 열을 출력한다.

      tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
..    ...     ...
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

In [ ]:
tips_df.sex
#특정 열만 출력하기
#닷 연산자를 통해 열에 접근할 수 있다.

0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): ['Male', 'Female']

In [ ]:
tips_df[tips_df.tip > 5]
#조건식
#위에 있는 조건은 tip 값이 5 초과인 데이터만 골라 출력한다

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
tips_df[(tips_df.sex == 'Female') & (tips_df.smoker == 'No')]
#여성 손님들 중에서, 비흡연자인 손님 데이터만 출력한다.

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
32        15.06  3.00  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
37        16.93  3.07  Female     No   Sat  Dinner     3
51        10.29  2.60  Female     No   Sun  Dinner     2
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
71        17.07  3.00  Female     No   Sat  Dinner     3
74        14.73  2.20  Female     No   Sat  Dinner     2
82        10.07  1.83  Female     No  Thur   Lunch     1
85        34.83  5.17  Female     No  Thur   Lunch     4
94        22.75  3.25  Female     No   Fri  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
114       25.71  4.00  Female     No   Sun  Dinner     3
115       17.31  3.50  Female     No   Sun  Dinner     2
117       10.65  1.50  Female     No  Thur   Lunch     2
118       12.43  1.80  Female     No  Thur   Lunch     2
119       24.08  2.92  Female     No  Thur   Lunch     4
121       13.42  1.68  Female     No  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
125       29.80  4.20  Female     No  Thur   Lunch     6
127       14.52  2.00  Female     No  Thur   Lunch     2
128       11.38  2.00  Female     No  Thur   Lunch     2
131       20.27  2.83  Female     No  Thur   Lunch     2
132       11.17  1.50  Female     No  Thur   Lunch     2
133       12.26  2.00  Female     No  Thur   Lunch     2
134       18.26  3.25  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
136       10.33  2.00  Female     No  Thur   Lunch     2
137       14.15  2.00  Female     No  Thur   Lunch     2
139       13.16  2.75  Female     No  Thur   Lunch     2
140       17.47  3.50  Female     No  Thur   Lunch     2
143       27.05  5.00  Female     No  Thur   Lunch     6
144       16.43  2.30  Female     No  Thur   Lunch     2
145        8.35  1.50  Female     No  Thur   Lunch     2
146       18.64  1.36  Female     No  Thur   Lunch     3
147       11.87  1.63  Female     No  Thur   Lunch     2
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
158       13.39  2.61  Female     No   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
223       15.98  3.00  Female     No   Fri   Lunch     3
238       35.83  4.67  Female     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
tips_df[tips_df['day'].isin(['Fri', 'Sat'])]
#isin: 특정 열의 특정 값만 골라 True 또는 False를 반환한다.
#즉 tips_df.day == 'Fri' & tips_df.day == 'Sat' 과 같다고 볼 수 있다.

     total_bill   tip     sex smoker  day    time  size
19        20.65  3.35    Male     No  Sat  Dinner     3
20        17.92  4.08    Male     No  Sat  Dinner     2
21        20.29  2.75  Female     No  Sat  Dinner     2
22        15.77  2.23  Female     No  Sat  Dinner     2
23        39.42  7.58    Male     No  Sat  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[106 rows x 7 columns]

In [ ]:
tips_df['total_paid'] = tips_df['total_bill'] + tips_df['tip']
#특정 열의 값을 추출해서 합한 후, 새 열에 할당하기
tips_df.loc[0 : 10, ['tip', 'total_bill', 'total_paid']]
#0~10, 특정 열만 골라 출력

     tip  total_bill  total_paid
0   1.01       16.99       18.00
1   1.66       10.34       12.00
2   3.50       21.01       24.51
3   3.31       23.68       26.99
4   3.61       24.59       28.20
5   4.71       25.29       30.00
6   2.00        8.77       10.77
7   3.12       26.88       30.00
8   1.96       15.04       17.00
9   3.23       14.78       18.01
10  1.71       10.27       11.98

In [ ]:
len(tips_df)
#데이터프레임의 길이

244

In [ ]:
tips_df.columns
#데이터프레임의 열 정보 출력

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'total_paid'],
      dtype='object')

In [ ]:
tips_df.index
#데이터프레임의 인덱스 정보

RangeIndex(start=0, stop=244, step=1)

In [ ]:
tips_df.values
#데이터프레임의 값 출력

array([[16.99, 1.01, 'Female', ..., 'Dinner', 2, 18.0],
       [10.34, 1.66, 'Male', ..., 'Dinner', 3, 12.0],
       [21.01, 3.5, 'Male', ..., 'Dinner', 3, 24.51],
       ...,
       [22.67, 2.0, 'Male', ..., 'Dinner', 2, 24.67],
       [17.82, 1.75, 'Male', ..., 'Dinner', 2, 19.57],
       [18.78, 3.0, 'Female', ..., 'Dinner', 2, 21.78]], dtype=object)

In [ ]:
tips_df.count() #열 별로 개수 세기

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
total_paid    244
dtype: int64

In [ ]:
# total_paid를 기준으로 내림차순 정렬
tips_df.sort_values(by = ['total_paid'], ascending=False)

     total_bill    tip     sex smoker   day    time  size  total_paid
170       50.81  10.00    Male    Yes   Sat  Dinner     3       60.81
212       48.33   9.00    Male     No   Sat  Dinner     4       57.33
59        48.27   6.73    Male     No   Sat  Dinner     4       55.00
156       48.17   5.00    Male     No   Sun  Dinner     6       53.17
182       45.35   3.50    Male    Yes   Sun  Dinner     3       48.85
..          ...    ...     ...    ...   ...     ...   ...         ...
218        7.74   1.44    Male    Yes   Sat  Dinner     2        9.18
195        7.56   1.44    Male     No  Thur   Lunch     2        9.00
111        7.25   1.00  Female     No   Sat  Dinner     1        8.25
92         5.75   1.00  Female    Yes   Fri  Dinner     2        6.75
67         3.07   1.00  Female    Yes   Sat  Dinner     1        4.07

[244 rows x 8 columns]

In [ ]:
tips.sum() #1,952
#행과 열의 합계를 출력한다
#sum 함수는 범주형 변수를 합할 수 없기 때문에 오류를 일으키는 것으로 보인다.

TypeError: 'Categorical' with dtype category does not support reduction 'sum'

In [ ]:
#시리즈 간 연결
s1 = pd.Series(
    [0, 1],
    index = [ 'A', 'B' ]
)

s2 = pd.Series(
    [2, 3, 4],
    index = [ 'c', 'd', 'e' ]
)

pd.concat([s1, s2])

A    0
B    1
c    2
d    3
e    4
dtype: int64

In [ ]:
#데프 간 연결
df1 = pd.DataFrame(
    [
        ['Dog', '3'],
        ['Lamb', '10'],
        ['Tiger', '6'],
        ['Moose', '3']
    ],
    index = ['0', '1', '2', '3'],
    columns = ['동물', '나이']
)

df2 = pd.DataFrame(
    [
        ['Home', '0'],
        ['Park', '2'],
        ['Forest', '0'],
        ['Park', '1'],
    ],
    index = ['0', '1', '2', '3'],
    columns = ['거주지', '뿔의 개수']
)

pd.concat([df1, df2], axis = 1)
#행 기준으로 연결?

      동물  나이     거주지 뿔의 개수
0    Dog   3    Home     0
1   Lamb  10    Park     2
2  Tiger   6  Forest     0
3  Moose   3    Park     1

In [ ]:
#데프 간 병합
df3 = pd.DataFrame(
    {
        '고객번호' : [1001, 1002, 1003, 1004, 1005, 1006, 1007],
        '이름' : ['강감찬', '이순신', '홍길동', '장보고', '유관순', '신사임당', '세종대왕']
    },
    columns = ['고객번호', '이름']
)

df4 = pd.DataFrame(
    {
        '고객번호' : [1001, 1001, 1005, 1006, 1008, 1001],
        '금액' : [10000, 20000, 30000, 40000, 50000, 60000]
    },
    columns = ['고객번호', '금액']
)

#inner join
#how 인수는 생략 가능
pd.merge(df3, df4, how = 'inner', on = '고객번호')

   고객번호    이름     금액
0  1001   강감찬  10000
1  1001   강감찬  20000
2  1001   강감찬  60000
3  1005   유관순  30000
4  1006  신사임당  40000

In [ ]:
#full join
#on 인수는 생략 가능
pd.merge(df3, df4, how = 'outer', on = '고객번호')

   고객번호    이름       금액
0  1001   강감찬  10000.0
1  1001   강감찬  20000.0
2  1001   강감찬  60000.0
3  1002   이순신      NaN
4  1003   홍길동      NaN
5  1004   장보고      NaN
6  1005   유관순  30000.0
7  1006  신사임당  40000.0
8  1007  세종대왕      NaN
9  1008   NaN  50000.0

In [ ]:
#좌측 병합
pd.merge(df3, df4, how = 'left')

   고객번호    이름       금액
0  1001   강감찬  10000.0
1  1001   강감찬  20000.0
2  1001   강감찬  60000.0
3  1002   이순신      NaN
4  1003   홍길동      NaN
5  1004   장보고      NaN
6  1005   유관순  30000.0
7  1006  신사임당  40000.0
8  1007  세종대왕      NaN

In [ ]:
#우측 병합
pd.merge(df3, df4, how = 'right')

   고객번호    이름     금액
0  1001   강감찬  10000
1  1001   강감찬  20000
2  1005   유관순  30000
3  1006  신사임당  40000
4  1008   NaN  50000
5  1001   강감찬  60000

In [ ]:
#범주형 변수의 값 개수 출력하기
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
tips['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
pd.crosstab(tips.sex, tips['day'])
#범주형 변수의 값들을 교차 분석

day     Thur  Fri  Sat  Sun
sex
Male      30   10   59   58
Female    32    9   28   18

In [ ]:
pd.crosstab(tips.sex, tips['day'], margins=True)
#여백 또는 총합(누적 값)

day     Thur  Fri  Sat  Sun  All
sex
Male      30   10   59   58  157
Female    32    9   28   18   87
All       62   19   87   76  244

In [ ]:
pd.crosstab(tips.sex, tips['day']).apply(lambda r: r / len(tips), axis = 1)
#전체 비율 출력

day         Thur       Fri       Sat       Sun
sex
Male    0.122951  0.040984  0.241803  0.237705
Female  0.131148  0.036885  0.114754  0.073770

In [ ]:
tips_df.describe()
#연속형 변수 별 개수, 평균, 표준, 최솟값, 최댓값, 4분위수를 출력한다.

       total_bill         tip        size  total_paid
count  244.000000  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672   22.784221
std      8.902412    1.383638    0.951100    9.890116
min      3.070000    1.000000    1.000000    4.070000
25%     13.347500    2.000000    2.000000   15.475000
50%     17.795000    2.900000    2.000000   20.600000
75%     24.127500    3.562500    3.000000   27.722500
max     50.810000   10.000000    6.000000   60.810000

In [ ]:
#연속형 변수만 추출
#select_dtypes - 특정 데이터형만 추출하는 함수
#include 인수는 자료형을 포함하고, exclude는 자료형을 제외시킨다.
continous_tips = tips_df.select_dtypes(exclude = ['category'])
#카테고리 형은 문자열형보다 성능과 속도 면에서 우수하다.
#연속형 변수 합하기
continous_tips.sum()

total_bill    4827.77
tip            731.58
size           627.00
total_paid    5559.35
dtype: float64