In [ ]:
import pandas as pd
#import google.colab as ggl

In [ ]:
#ggl.drive.mount("/content/gdrive")
path = "./exam_sample.csv"

df = pd.read_csv(path, encoding="cp949", engine="python")

In [3]:
df2 = df.groupby(["class"])
df2_A = df2.get_group("A")
df2_B = df2.get_group("B")

/tmp/ipykernel_11312/3567608341.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df2_A = df2.get_group("A")
/tmp/ipykernel_11312/3567608341.py:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df2_B = df2.get_group("B")

In [4]:
df.groupby(["class", "sex"]).mean()

           student_no  science  english  math
class sex
A     m           2.5     54.0     98.0  40.0
      w           2.5     69.0     91.5  52.5
B     m           6.5     71.5     89.5  65.0
      w           6.5     45.0     79.0  90.0
C     w           9.5     30.0     95.5  35.0

In [5]:
df.math.groupby([df["class"], df.sex]).mean()

class  sex
A      m      40.0
       w      52.5
B      m      65.0
       w      90.0
C      w      35.0
Name: math, dtype: float64

In [6]:
df.math.groupby([df["class"], df.sex]).count()

class  sex
A      m      2
       w      2
B      m      2
       w      2
C      w      2
Name: math, dtype: int64

In [7]:
df_class = df.groupby(["class"])
df_class_B = df_class.get_group("B")
df_class_B[["math", "english"]]

/tmp/ipykernel_11312/3206911046.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df_class_B = df_class.get_group("B")

   math  english
4    90       80
5    50       89
6    80       90
7    90       78

In [8]:
df_math_cut = pd.cut(df.math, 3)
df_math_cut

0    (43.333, 66.667]
1    (43.333, 66.667]
2    (43.333, 66.667]
3     (19.93, 43.333]
4      (66.667, 90.0]
5    (43.333, 66.667]
6      (66.667, 90.0]
7      (66.667, 90.0]
8     (19.93, 43.333]
9    (43.333, 66.667]
Name: math, dtype: category
Categories (3, interval[float64, right]): [(19.93, 43.333] < (43.333, 66.667] < (66.667, 90.0]]

In [9]:
import numpy as np

df_math_qcut = pd.qcut(df.math, 3, labels=False)
df_math_qcut

0    1
1    2
2    0
3    0
4    2
5    1
6    2
7    2
8    0
9    1
Name: math, dtype: int64

In [12]:
df_math_qcut = pd.qcut(df.math, 3, labels=np.arange(3, 0, -1))
df_math_qcut

0    2
1    1
2    3
3    3
4    1
5    2
6    1
7    1
8    3
9    2
Name: math, dtype: category
Categories (3, int64): [3 < 2 < 1]

In [19]:
df_math_qcut_L = df.math.groupby(df_math_qcut)
df_math_qcut_L3 = df_math_qcut_L.get_group(1)
df_math_qcut_L3

/tmp/ipykernel_11312/3549129318.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_math_qcut_L = df.math.groupby(df_math_qcut)

1    60
4    90
6    80
7    90
Name: math, dtype: int64

In [21]:
df_math_qcut_L.agg(["count", "mean", "std", "min", "max"])

      count       mean        std  min  max
math
3         3  31.666667  12.583057   20   45
2         3  50.000000   0.000000   50   50
1         4  80.000000  14.142136   60   90

In [22]:
#원핫 인코딩
pd.get_dummies(df)

   student_no  science  english  math  class_A  class_B  class_C  sex_m  sex_w
0           1       50       98    50     True    False    False   True  False
1           2       60       97    60     True    False    False  False   True
2           3       78       86    45     True    False    False  False   True
3           4       58       98    30     True    False    False   True  False
4           5       65       80    90    False     True    False  False   True
5           6       98       89    50    False     True    False   True  False
6           7       45       90    80    False     True    False   True  False
7           8       25       78    90    False     True    False  False   True
8           9       15       98    20    False    False     True  False   True
9          10       45       93    50    False    False     True  False   True

In [24]:
pd.get_dummies(df[["class", "sex"]])

   class_A  class_B  class_C  sex_m  sex_w
0     True    False    False   True  False
1     True    False    False  False   True
2     True    False    False  False   True
3     True    False    False   True  False
4    False     True    False  False   True
5    False     True    False   True  False
6    False     True    False   True  False
7    False     True    False  False   True
8    False    False     True  False   True
9    False    False     True  False   True

In [23]:
df.T

             0   1   2   3   4   5   6   7   8   9
student_no   1   2   3   4   5   6   7   8   9  10
class        A   A   A   A   B   B   B   B   C   C
science     50  60  78  58  65  98  45  25  15  45
english     98  97  86  98  80  89  90  78  98  93
math        50  60  45  30  90  50  80  90  20  50
sex          m   w   w   m   w   m   m   w   w   w

In [25]:
df.pivot_table(index="class", columns="sex", values="science")
#필요한 데이터만 추출
#클래스, 인스턴스 모두 사용 가능한 함수

sex       m     w
class
A      54.0  69.0
B      71.5  45.0
C       NaN  30.0

In [26]:
pd.melt(df, id_vars=["student_no", "class"])
#열의 변수를 행으로 재구조화

    student_no class variable value
0            1     A  science    50
1            2     A  science    60
2            3     A  science    78
3            4     A  science    58
4            5     B  science    65
5            6     B  science    98
6            7     B  science    45
7            8     B  science    25
8            9     C  science    15
9           10     C  science    45
10           1     A  english    98
11           2     A  english    97
12           3     A  english    86
13           4     A  english    98
14           5     B  english    80
15           6     B  english    89
16           7     B  english    90
17           8     B  english    78
18           9     C  english    98
19          10     C  english    93
20           1     A     math    50
21           2     A     math    60
22           3     A     math    45
23           4     A     math    30
24           5     B     math    90
25           6     B     math    50
26           7     B     math    80
27           8     B     math    90
28           9     C     math    20
29          10     C     math    50
30           1     A      sex     m
31           2     A      sex     w
32           3     A      sex     w
33           4     A      sex     m
34           5     B      sex     w
35           6     B      sex     m
36           7     B      sex     m
37           8     B      sex     w
38           9     C      sex     w
39          10     C      sex     w

In [29]:
df.stack(-1)

0  student_no     1
   class          A
   science       50
   english       98
   math          50
   sex            m
1  student_no     2
   class          A
   science       60
   english       97
   math          60
   sex            w
2  student_no     3
   class          A
   science       78
   english       86
   math          45
   sex            w
3  student_no     4
   class          A
   science       58
   english       98
   math          30
   sex            m
4  student_no     5
   class          B
   science       65
   english       80
   math          90
   sex            w
5  student_no     6
   class          B
   science       98
   english       89
   math          50
   sex            m
6  student_no     7
   class          B
   science       45
   english       90
   math          80
   sex            m
7  student_no     8
   class          B
   science       25
   english       78
   math          90
   sex            w
8  student_no     9
   class          C
   science       15
   english       98
   math          20
   sex            w
9  student_no    10
   class          C
   science       45
   english       93
   math          50
   sex            w
dtype: object

In [30]:
data_timeseries = pd.read_csv(f"{path}/timeseries.csv")
data_timeseries

         Date  Close  Start   High    Low  Volume
0  2015-07-02  10100  10850  10900  10000  137977
1  2016-06-29  10700  10550  10900   9990  170253
2  2017-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2019-06-26  10800  10900  11000  10700   63039

In [32]:
ts_date = pd.to_datetime(data_timeseries.Date)
ts_date

0   2015-07-02
1   2016-06-29
2   2017-06-28
3   2018-06-27
4   2019-06-26
Name: Date, dtype: datetime64[ns]

In [38]:
ts_day = ts_date.dt.to_period(freq="D")
ts_day

0    2015-07-02
1    2016-06-29
2    2017-06-28
3    2018-06-27
4    2019-06-26
Name: Date, dtype: period[D]

In [40]:
ts_mon = ts_date.dt.to_period(freq="M")
ts_mon

0    2015-07
1    2016-06
2    2017-06
3    2018-06
4    2019-06
Name: Date, dtype: period[M]

In [42]:
ts_yrs = ts_date.dt.to_period(freq="a")
ts_yrs

/tmp/ipykernel_11312/2544572097.py:1: FutureWarning: 'a' is deprecated and will be removed in a future version, please use 'Y' instead.
  ts_yrs = ts_date.dt.to_period(freq="a")
/tmp/ipykernel_11312/2544572097.py:1: FutureWarning: 'a' is deprecated and will be removed in a future version, please use 'A' instead.
  ts_yrs = ts_date.dt.to_period(freq="a")

0    2015
1    2016
2    2017
3    2018
4    2019
Name: Date, dtype: period[Y-DEC]