In [ ]:
import pandas as pd
import numpy as np
#import google.colab as ggl

In [37]:
#ggl.drive.mount("/content/gdrive")
path = "./"

df = pd.read_csv(f"{path}/exam_sample.csv", encoding="cp949", engine="python")
df

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m
4           5     B       65       80    90   w
5           6     B       98       89    50   m
6           7     B       45       90    80   m
7           8     B       25       78    90   w
8           9     C       15       98    20   w
9          10     C       45       93    50   w

In [38]:
df_class = df.groupby(["class"]) #class 별로 나누기
df_class

In [39]:
class_A = df_class.get_group(("A",))
class_B = df_class.get_group(("B",))
class_C = df_class.get_group(("C",))
#튜플 형식으로 그룹 탐색 <- 아니면 KeyError 발생함
class_A

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m

In [40]:
df.groupby(df["class"]).math.mean()
#반별 수학 점수 평균
#아래 셀과 똑같은 코드다

class
A    46.25
B    77.50
C    35.00
Name: math, dtype: float64

In [41]:
df.math.groupby(df["class"]).mean()

class
A    46.25
B    77.50
C    35.00
Name: math, dtype: float64

In [42]:
df.groupby(["class", "sex"]).mean()
#반별 성별 평균

           student_no  science  english  math
class sex
A     m           2.5     54.0     98.0  40.0
      w           2.5     69.0     91.5  52.5
B     m           6.5     71.5     89.5  65.0
      w           6.5     45.0     79.0  90.0
C     w           9.5     30.0     95.5  35.0

In [43]:
df.math.groupby([df["class"], df.sex]).mean()
#반별 성별 수학 점수 평균

class  sex
A      m      40.0
       w      52.5
B      m      65.0
       w      90.0
C      w      35.0
Name: math, dtype: float64

In [44]:
df.math.groupby([df["class"], df.sex]).count()
#반별 성별 수학 점수 개수

class  sex
A      m      2
       w      2
B      m      2
       w      2
C      w      2
Name: math, dtype: int64

In [45]:
class_B[["math", "english"]]
#B반의 수학과 영어 점수수

   math  english
4    90       80
5    50       89
6    80       90
7    90       78

In [46]:
#수학 점수를 3개 구단으로 나누기 -> 연속형을 범주형으로 변환
#pandas의 cut 함수: 동일 길이로 나눈다.
df_math_cut = pd.cut(df.math, 3)
df_math_cut

0    (43.333, 66.667]
1    (43.333, 66.667]
2    (43.333, 66.667]
3     (19.93, 43.333]
4      (66.667, 90.0]
5    (43.333, 66.667]
6      (66.667, 90.0]
7      (66.667, 90.0]
8     (19.93, 43.333]
9    (43.333, 66.667]
Name: math, dtype: category
Categories (3, interval[float64, right]): [(19.93, 43.333] < (43.333, 66.667] < (66.667, 90.0]]

In [47]:
group1 = df.math.groupby(df_math_cut)
group1.agg(["count", "mean", "std", "min", "max"])
#구간마다 개수, 평균, 표준편차, 최솟값, 최댓값 구하기

                  count       mean       std  min  max
math
(19.93, 43.333]       2  25.000000  7.071068   20   30
(43.333, 66.667]      5  51.000000  5.477226   45   60
(66.667, 90.0]        3  86.666667  5.773503   80   90

In [ ]:
#pandas의 qcut 함수: 동일 개수로 나눈다.
#labels 인자를 false로 설정하면 (0, 1, 2)구간을 0부터 순차적으로 +1 한다.
df_math_qcut = pd.qcut(df.math, 3, labels=False)
df_math_qcut

0    0
1    1
2    0
3    0
4    2
5    0
6    2
7    2
8    0
9    0
Name: math, dtype: int64

In [49]:
#구간을 3부터 1까지 -1 한다. <- 이해 못함
#구간을 3부터 1까지 3등분한다.
df_math_qcut = pd.qcut(df.math, 3, labels=np.arange(3, 0, -1))
df_math_qcut

0    3
1    2
2    3
3    3
4    1
5    3
6    1
7    1
8    3
9    3
Name: math, dtype: category
Categories (3, int64): [3 < 2 < 1]

In [50]:
group2 = df.math.groupby(df_math_qcut)
grade_1 = group2.get_group(1)
grade_1

4    90
6    80
7    90
Name: math, dtype: int64

In [51]:
group2.agg(["count", "mean", "std", "min", "max"])

      count       mean        std  min  max
math
3         6  40.833333  12.812754   20   50
2         1  60.000000        NaN   60   60
1         3  86.666667   5.773503   80   90

In [52]:
#원핫 인코딩; 범주형 데이터를 (0, 1)로 변환한다
pd.get_dummies(df)

   student_no  science  english  math  class_A  class_B  class_C  sex_m  sex_w
0           1       50       98    50     True    False    False   True  False
1           2       60       97    60     True    False    False  False   True
2           3       78       86    45     True    False    False  False   True
3           4       58       98    30     True    False    False   True  False
4           5       65       80    90    False     True    False  False   True
5           6       98       89    50    False     True    False   True  False
6           7       45       90    80    False     True    False   True  False
7           8       25       78    90    False     True    False  False   True
8           9       15       98    20    False    False     True  False   True
9          10       45       93    50    False    False     True  False   True

In [53]:
#특정 열만 골라서 원핫 인코딩할 수도 있다.
#고른 것이 전부 범주형
pd.get_dummies(df[["class", "sex"]])

   class_A  class_B  class_C  sex_m  sex_w
0     True    False    False   True  False
1     True    False    False  False   True
2     True    False    False  False   True
3     True    False    False   True  False
4    False     True    False  False   True
5    False     True    False   True  False
6    False     True    False   True  False
7    False     True    False  False   True
8    False    False     True  False   True
9    False    False     True  False   True

In [54]:
df.T
#데프 전치시키기
#행과 열을 맞바꾸는 함수
#아는 내용이지 히히

             0   1   2   3   4   5   6   7   8   9
student_no   1   2   3   4   5   6   7   8   9  10
class        A   A   A   A   B   B   B   B   C   C
science     50  60  78  58  65  98  45  25  15  45
english     98  97  86  98  80  89  90  78  98  93
math        50  60  45  30  90  50  80  90  20  50
sex          m   w   w   m   w   m   m   w   w   w

In [55]:
#필요한 데이터만 추출
df.pivot_table(index="class", columns="sex", values="science")
#행 인덱스는 class, 열 인덱스는 sex, 과학 점수
#클래스, 인스턴스 모두 사용 가능한 함수

sex       m     w
class
A      54.0  69.0
B      71.5  45.0
C       NaN  30.0

In [56]:
pd.melt(df, id_vars=["student_no", "class"])
#열의 변수를 행으로 재구조화 <- 무슨 소리야
#즉 id_vars를 제외한 모든 열과 열의 요소를 행으로 옮긴다.

    student_no class variable value
0            1     A  science    50
1            2     A  science    60
2            3     A  science    78
3            4     A  science    58
4            5     B  science    65
5            6     B  science    98
6            7     B  science    45
7            8     B  science    25
8            9     C  science    15
9           10     C  science    45
10           1     A  english    98
11           2     A  english    97
12           3     A  english    86
13           4     A  english    98
14           5     B  english    80
15           6     B  english    89
16           7     B  english    90
17           8     B  english    78
18           9     C  english    98
19          10     C  english    93
20           1     A     math    50
21           2     A     math    60
22           3     A     math    45
23           4     A     math    30
24           5     B     math    90
25           6     B     math    50
26           7     B     math    80
27           8     B     math    90
28           9     C     math    20
29          10     C     math    50
30           1     A      sex     m
31           2     A      sex     w
32           3     A      sex     w
33           4     A      sex     m
34           5     B      sex     w
35           6     B      sex     m
36           7     B      sex     m
37           8     B      sex     w
38           9     C      sex     w
39          10     C      sex     w

In [57]:
stack = df.stack(-1)
#열 인덱스가 행 인덱스로 변환한다.
#열 인덱스가 반시계 방향으로 90도 회전한 것과 같다.

stack

0  student_no     1
   class          A
   science       50
   english       98
   math          50
   sex            m
1  student_no     2
   class          A
   science       60
   english       97
   math          60
   sex            w
2  student_no     3
   class          A
   science       78
   english       86
   math          45
   sex            w
3  student_no     4
   class          A
   science       58
   english       98
   math          30
   sex            m
4  student_no     5
   class          B
   science       65
   english       80
   math          90
   sex            w
5  student_no     6
   class          B
   science       98
   english       89
   math          50
   sex            m
6  student_no     7
   class          B
   science       45
   english       90
   math          80
   sex            m
7  student_no     8
   class          B
   science       25
   english       78
   math          90
   sex            w
8  student_no     9
   class          C
   science       15
   english       98
   math          20
   sex            w
9  student_no    10
   class          C
   science       45
   english       93
   math          50
   sex            w
dtype: object

In [58]:
#unstack 함수는 stack의 반대
unstack = stack.unstack()
unstack

  student_no class science english math sex
0          1     A      50      98   50   m
1          2     A      60      97   60   w
2          3     A      78      86   45   w
3          4     A      58      98   30   m
4          5     B      65      80   90   w
5          6     B      98      89   50   m
6          7     B      45      90   80   m
7          8     B      25      78   90   w
8          9     C      15      98   20   w
9         10     C      45      93   50   w

In [59]:
unstack2 = df.unstack(level=-1) #<-??
unstack2

student_no  0     1
            1     2
            2     3
            3     4
            4     5
            5     6
            6     7
            7     8
            8     9
            9    10
class       0     A
            1     A
            2     A
            3     A
            4     B
            5     B
            6     B
            7     B
            8     C
            9     C
science     0    50
            1    60
            2    78
            3    58
            4    65
            5    98
            6    45
            7    25
            8    15
            9    45
english     0    98
            1    97
            2    86
            3    98
            4    80
            5    89
            6    90
            7    78
            8    98
            9    93
math        0    50
            1    60
            2    45
            3    30
            4    90
            5    50
            6    80
            7    90
            8    20
            9    50
sex         0     m
            1     w
            2     w
            3     m
            4     w
            5     m
            6     m
            7     w
            8     w
            9     w
dtype: object